services:

  node-chrome-1:
    image: selenium/node-chrome:145.0-20260222
    restart: on-failure
    shm_size: 3gb
    networks:
      - grid
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  node-chrome-2:
    image: selenium/node-chrome:145.0-20260222
    restart: on-failure
    shm_size: 3gb
    networks:
      - grid
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

networks:
  grid:
    external: true
    name: selenium-grid-network