services:
  orangehrm:
    image: orangehrm/orangehrm:5.8
    container_name: orangehrm
    ports:
      - "9000:80"
    networks:
      - qa-network
    volumes:
      - orangehrm_data:/var/www/html

volumes:
  orangehrm_data:
    name: qa-orangehrm-data

networks:
  qa-network:
    external: true