services:
  selenium-hub:
    image: selenium/hub:4.41.0
    container_name: selenium-hub
    restart: on-failure
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid

networks:
  grid:
    name: selenium-grid-network